// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmVZGLxFjYJsACMTHaByEyF2yShi-0TDs',
    appId: '1:697506895162:web:de175f966005d564e5ec03',
    messagingSenderId: '697506895162',
    projectId: 'redfuj-7f991',
    authDomain: 'redfuj-7f991.firebaseapp.com',
    storageBucket: 'redfuj-7f991.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5wehk9z05cVmrWHvSlL0plNf_E2EVD-c',
    appId: '1:697506895162:android:056fa78c693d55b4e5ec03',
    messagingSenderId: '697506895162',
    projectId: 'redfuj-7f991',
    storageBucket: 'redfuj-7f991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANxiGHDvqJTOy3SzKDa6F18KWcdWlBCmA',
    appId: '1:697506895162:ios:57701351ad3ce0cce5ec03',
    messagingSenderId: '697506895162',
    projectId: 'redfuj-7f991',
    storageBucket: 'redfuj-7f991.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANxiGHDvqJTOy3SzKDa6F18KWcdWlBCmA',
    appId: '1:697506895162:ios:dbadd1350d0ba40ce5ec03',
    messagingSenderId: '697506895162',
    projectId: 'redfuj-7f991',
    storageBucket: 'redfuj-7f991.appspot.com',
    iosBundleId: 'com.example.store.RunnerTests',
  );
}
